const sampleProducts = [
  // MEN
  {
    image: "https://static.nike.com/a/videos/so_0.5/8d9920f5-1e17-4857-92d5-5a1a54ccec97/dri-fit-fitness-t-shirt-PDvL9m.jpg",
    title: "Nike Dri-FIT Tee",
    description: "Moisture‑wicking tee ideal for sports and casual wear.",
    category: "men",
    brand: "nike",
    price: 2200,
    salePrice: 1899,
    totalStock: 70,
    averageReview: 4.5,
  },
  {
    image: "https://i.otto.de/i/otto/133a8eca-112e-50ef-b36b-525a701b4b62/adidas-performance-shorts-essentials-short.jpg?$formatz$",
    title: "Adidas Performance Shorts",
    description: "Breathable running shorts for men.",
    category: "men",
    brand: "adidas",
    price: 1800,
    salePrice: 1599,
    totalStock: 60,
    averageReview: 4.3,
  },
  {
    image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/519018/01/mod01/fnd/PNA/fmt/png/Reactive-Men's-Sleeveless-Training-Hoodie",
    title: "Puma Training Hoodie",
    description: "Warm and cozy hoodie for workouts and casual wear.",
    category: "men",
    brand: "puma",
    price: 3800,
    salePrice: 3499,
    totalStock: 40,
    averageReview: 4.4,
  },
  {
    image: "https://i5.walmartimages.com/asr/acb85158-dd30-4d7b-bfee-4044f4a236c4_1.2e86d110358833ded644bb2b6e719381.jpeg",
    title: "Levi's Relaxed Denim",
    description: "Comfortable relaxed fit jeans for daily wear.",
    category: "men",
    brand: "levi",
    price: 4000,
    salePrice: 3599,
    totalStock: 50,
    averageReview: 4.6,
  },
  {
    image: "https://www.simonjersey.com/images/uneek-unisex-100-cotton-polo-shirt-red-p2608-199166_image.jpg",
    title: "H&M Cotton Polo",
    description: "Classic polo shirt in soft cotton.",
    category: "men",
    brand: "h&m",
    price: 1600,
    salePrice: 1399,
    totalStock: 80,
    averageReview: 4.2,
  },
  {
    image: "https://i.pinimg.com/originals/57/4b/4a/574b4aa5060694f358e1efa6005959df.jpg",
    title: "Zara Slim Fit Chinos",
    description: "Stylish chinos for smart-casual occasions.",
    category: "men",
    brand: "zara",
    price: 3200,
    salePrice: 2999,
    totalStock: 45,
    averageReview: 4.3,
  },

  // WOMEN
  {
    image: "https://tse2.mm.bing.net/th?id=OIP.yUOL_K0lK3S5e_qiDZrDaQHaLW&pid=Api&P=0&w=300&h=300",
    title: "Zara Wrap Dress",
    description: "Elegant wrap dress for day-to-night styling.",
    category: "women",
    brand: "zara",
    price: 4500,
    salePrice: 3999,
    totalStock: 35,
    averageReview: 4.7,
  },
  {
    image: "https://assets.myntassets.com/h_200,w_200,c_fill,g_auto/h_1440,q_100,w_1080/v1/assets/images/12081756/2020/7/13/26c424d7-7cc8-4e24-8ea8-9998785788f31594643088649Linen-blendshirt1.jpg",
    title: "H&M Linen Blouse",
    description: "Lightweight linen blouse for summer.",
    category: "women",
    brand: "h&m",
    price: 2000,
    salePrice: 1799,
    totalStock: 60,
    averageReview: 4.5,
  },
  {
    image: "https://images.asos-media.com/products/nike-yoga-leggings-in-black/14896353-1-black?$n_640w$&wid=513&fit=constrain",
    title: "Nike Yoga Leggings",
    description: "High‑waist stretchy yoga leggings.",
    category: "women",
    brand: "nike",
    price: 3000,
    salePrice: 2799,
    totalStock: 55,
    averageReview: 4.8,
  },
  {
    image: "https://tse2.mm.bing.net/th?id=OIP.gRmjJBg1Y2wnTBhTUCvRfgHaIj&pid=Api&P=0&w=300&h=300",
    title: "Adidas Track Jacket",
    description: "Zip‑up track jacket in classic style.",
    category: "women",
    brand: "adidas",
    price: 4200,
    salePrice: 3899,
    totalStock: 40,
    averageReview: 4.6,
  },
  {
    image: "https://cdna.lystit.com/photos/shopbop/8a25b465/levis-Black-Mark-Deconstructed-Skirt.jpeg",
    title: "Levi's Denim Skirt",
    description: "Mid‑length denim skirt with classic look.",
    category: "women",
    brand: "levi",
    price: 3500,
    salePrice: 3199,
    totalStock: 30,
    averageReview: 4.5,
  },
  {
    image: "https://tse1.mm.bing.net/th?id=OIP.if8hIjv59tRrob9rMldEUgHaHa&pid=Api&P=0&w=300&h=300",
    title: "Puma Casual Tee",
    description: "Relaxed-fit tee for everyday styling.",
    category: "women",
    brand: "puma",
    price: 1800,
    salePrice: 1599,
    totalStock: 70,
    averageReview: 4.4,
  },

  // KIDS
  {
    image: "https://tse2.mm.bing.net/th?id=OIP.UwCpXrpSCKhugVS_TT_OtAHaHa&pid=Api&P=0&w=300&h=300",
    title: "Puma Kids Sneakers",
    description: "Colorful comfy sneakers for kids.",
    category: "kids",
    brand: "puma",
    price: 2500,
    salePrice: 2299,
    totalStock: 30,
    averageReview: 4.2,
  },
  {
    image: "https://tse2.mm.bing.net/th?id=OIP.PS5mqCTBf8t3fdM7UDkg3gHaJQ&pid=Api&P=0&w=300&h=300",
    title: "Adidas Kids T‑Shirt",
    description: "Soft cotton tee with print for kids.",
    category: "kids",
    brand: "adidas",
    price: 1200,
    salePrice: 999,
    totalStock: 50,
    averageReview: 4.5,
  },
  {
    image: "https://i.pinimg.com/originals/eb/22/d7/eb22d75caea6b218a7a4219d18601128.jpg",
    title: "Nike Toddler Shorts",
    description: "Comfortable shorts for toddlers.",
    category: "kids",
    brand: "nike",
    price: 1500,
    salePrice: 1299,
    totalStock: 40,
    averageReview: 4.3,
  },
  {
    image: "https://i.etsystatic.com/25120665/r/il/40eacd/2694653356/il_1140xN.2694653356_bj6w.jpg",
    title: "Zara Kids Hoodie",
    description: "Warm hoodie for children.",
    category: "kids",
    brand: "zara",
    price: 2000,
    salePrice: 1799,
    totalStock: 25,
    averageReview: 4.6,
  },
  {
    image: "https://i.pinimg.com/originals/34/8f/95/348f95ac76a28773e89e9e4cfb6a1c99.jpg",
    title: "H&M Kids Joggers",
    description: "Soft joggers for active kids.",
    category: "kids",
    brand: "h&m",
    price: 1800,
    salePrice: 1599,
    totalStock: 45,
    averageReview: 4.4,
  },

  // ACCESSORIES
  {
    image: "https://tse1.mm.bing.net/th?id=OIP.H_w4kZwsKLnVk5cgAXBJXwHaHa&pid=Api&P=0&w=300&h=300",
    title: "Nike Cap",
    description: "Adjustable cotton sports cap.",
    category: "accessories",
    brand: "nike",
    price: 900,
    salePrice: 799,
    totalStock: 120,
    averageReview: 4.1,
  },
  {
    image: "https://images.asos-media.com/products/levis-leather-belt-in-tan-with-circle-buckle/205414238-1-mediumbrown?$n_640w$&wid=513&fit=constrain",
    title: "Levi's Leather Belt",
    description: "Stylish leather belt.",
    category: "accessories",
    brand: "levi",
    price: 2500,
    salePrice: 2199,
    totalStock: 60,
    averageReview: 4.6,
  },
  {
    image: "https://tse3.mm.bing.net/th?id=OIP.MKVrqe0kDrpPNwWz3OCWJQHaIz&pid=Api&P=0&w=300&h=300",
    title: "Adidas Sling Bag",
    description: "Compact sling bag for essentials.",
    category: "accessories",
    brand: "adidas",
    price: 3200,
    salePrice: 2899,
    totalStock: 50,
    averageReview: 4.5,
  },
  {
    image: "https://images.puma.com/image/upload/f_auto,q_auto,t_vertical_model,w_600/global/054305/01/mod03/fnd/EEA/fmt/png/PUMA-Fit-Training-Wristbands",
    title: "Puma Wristband",
    description: "Stretchy sports wristband.",
    category: "accessories",
    brand: "puma",
    price: 700,
    salePrice: 599,
    totalStock: 100,
    averageReview: 4.2,
  },
  {
    image: "https://lp2.hm.com/hmgoepprod?set=quality[79]%2Csource[%2Fb3%2F3f%2Fb33f70531698d07bbfc909f1e1ba5ae61f72b453.jpg]%2Corigin[dam]%2Ccategory[ladies_accessories_sunglasses]%2Ctype[DESCRIPTIVESTILLLIFE]%2Cres[m]%2Chmver[1]&call=url[file:/product/main]",
    title: "H&M Sunglasses",
    description: "Stylish UV-protective sunglasses.",
    category: "accessories",
    brand: "h&m",
    price: 1800,
    salePrice: 1599,
    totalStock: 40,
    averageReview: 4.4,
  },

  // FOOTWEAR
  {
    image: "https://assets.adidas.com/images/w_1880,f_auto,q_auto/96fa7303d14249b7af33af9c00a79c5c_9366/GX9775_01_standard.jpg",
    title: "Adidas Running Shoes",
    description: "Lightweight shoes for all-day comfort.",
    category: "footwear",
    brand: "adidas",
    price: 5000,
    salePrice: 4499,
    totalStock: 80,
    averageReview: 4.7,
  },
  {
    image: "https://images.fancode.com/media/catalog/product/cache/c864083bf74ae97037fa23bc5340ae95/1/0/10785301_4_uazcxiuchl4qrkmi.jpg",
    title: "Puma Flip Flops",
    description: "Beach-ready casual flip flops.",
    category: "footwear",
    brand: "puma",
    price: 1200,
    salePrice: 999,
    totalStock: 100,
    averageReview: 4.3,
  },
  {
    image: "https://cdn.shopify.com/s/files/1/2114/6025/files/Nike-Ja-1-4_1024x1024.png?v=1672171309",
    title: "Nike Basketball Shoes",
    description: "High‑performance shoes for the court.",
    category: "footwear",
    brand: "nike",
    price: 6000,
    salePrice: 5499,
    totalStock: 50,
    averageReview: 4.8,
  },
  {
    image: "https://tse1.mm.bing.net/th?id=OIP.SMgJ1FWp6qylX2SRXCH2fQHaHa&pid=Api&P=0&w=300&h=300",
    title: "Levi's Casual Loafers",
    description: "Classic suede loafers.",
    category: "footwear",
    brand: "levi",
    price: 4500,
    salePrice: 4099,
    totalStock: 30,
    averageReview: 4.5,
  },
  {
    image: "https://dynamic.zacdn.com/kyjsJkWOLkYjh_4glLT17NP3WoU=/filters:quality(70):format(webp)/https://static-sg.zacdn.com/p/hm-7217-5746703-2.jpg",
    title: "H&M Platform Sandals",
    description: "Trendy platform sandals.",
    category: "footwear",
    brand: "h&m",
    price: 2800,
    salePrice: 2499,
    totalStock: 55,
    averageReview: 4.4,
  },
];

const sampleFeatures = [
  {
    image: "https://mir-s3-cdn-cf.behance.net/project_modules/1400/1e43a062632241.5a96943231a74.jpg",
  },
  {
    image: "https://marketplace.canva.com/EAFYElY5EE4/1/0/1600w/canva-brown-and-white-modern-fashion-banner-landscape-Ap8IU9nEbh8.jpg",
  },
  {
    image: "https://wallpaperaccess.com/full/1640152.jpg",
  },
  {
    image: "https://i.pinimg.com/originals/9a/71/6f/9a716f90fc2e24079b8960168d5ea089.jpg",
  },
  {
    image: "https://marketplace.canva.com/EAFVHstxnwk/1/0/800w/canva-beige-aesthetic-exclusive-fashion-wear-collection-clothing-banner-yv-HRWs1aMc.jpg",
  },
];

module.exports = { ProductData: sampleProducts, FeatureData: sampleFeatures };
